import { expect, type Page } from '@playwright/test';

export const TRUST_LOCALES = ['en', 'de', 'tr', 'ru', 'uk'] as const;
export type TrustLocale = (typeof TRUST_LOCALES)[number];

export const TRUST_MESSAGES: Record<TrustLocale, { disclaimer: string; aiLabel: string }> = {
  en: {
    disclaimer:
      'This is an automated overview, not medical advice. Talk to your doctor before changing any treatment.',
    aiLabel: 'Summaries are generated by AI from the linked sources.',
  },
  de: {
    disclaimer:
      'Dies ist eine automatisierte Übersicht, keine medizinische Beratung. Sprechen Sie mit Ihrem Arzt, bevor Sie eine Behandlung ändern.',
    aiLabel: 'Zusammenfassungen werden von KI aus den verlinkten Quellen erstellt.',
  },
  tr: {
    disclaimer:
      'Bu otomatik bir özet, tıbbi tavsiye değildir. Tedavide herhangi bir değişiklik yapmadan önce doktorunuzla konuşun.',
    aiLabel: 'Özetler, bağlantılı kaynaklardan yapay zeka ile oluşturulmuştur.',
  },
  ru: {
    disclaimer:
      'Это автоматический обзор, а не медицинская рекомендация. Проконсультируйтесь с врачом, прежде чем менять лечение.',
    aiLabel: 'Краткие изложения созданы ИИ на основе указанных источников.',
  },
  uk: {
    disclaimer:
      'Це автоматичний огляд, а не медична порада. Проконсультуйтеся з лікарем, перш ніж змінювати лікування.',
    aiLabel: 'Стислі виклади створені ШІ на основі вказаних джерел.',
  },
};

export async function expectTrustNotice(page: Page, locale: TrustLocale) {
  const messages = TRUST_MESSAGES[locale];
  await expect(page.getByText(messages.disclaimer)).toBeVisible();
  await expect(page.getByText(messages.aiLabel)).toBeVisible();
}
