/** Fixed sentence when Russian text is still missing after the wait (ru and en emails). */
export const RUSSIAN_FALLBACK_NOTE = 'Перевод этого выпуска недоступен.';

export const EMAIL_COPY = {
  en: {
    disclaimer:
      'This is an automated overview, not medical advice. Talk to your doctor before changing any treatment.',
    aiLabel: 'Summaries are generated by AI from the linked sources.',
    trial: 'Trial registration',
    unsubscribe: 'Unsubscribe',
    privacy: 'Privacy',
    issue: 'Read this issue',
  },
  ru: {
    disclaimer:
      'Это автоматический обзор, а не медицинская рекомендация. Проконсультируйтесь с врачом, прежде чем менять лечение.',
    aiLabel: 'Краткие изложения созданы ИИ на основе указанных источников.',
    trial: 'Регистрация исследования',
    unsubscribe: 'Отписаться',
    privacy: 'Конфиденциальность',
    issue: 'Читать выпуск',
  },
} as const;

export type EmailLanguage = 'en' | 'ru';

export type IssueEmailItem = {
  title: string;
  source: string;
  date: string | null;
  sentence: string;
  isTrial: boolean;
};

export type IssueEmailContent = {
  date: string;
  summaryPoints: string[];
  items: IssueEmailItem[];
};

export type IssueEmailLinks = {
  issue: string;
  privacy: string;
  unsubscribe: string;
};

export type IssueEmail = {
  subject: string;
  text: string;
  html: string;
};

function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function itemLines(item: IssueEmailItem, trialLabel: string): string[] {
  const when = item.date ? `${item.source} · ${item.date}` : item.source;
  const lines = [item.title, when, item.sentence];
  if (item.isTrial) lines.push(trialLabel);
  return lines;
}

/**
 * Plain text and HTML carry the same information. The plain text stays readable
 * after every URL is removed: names, dates, points, items, disclaimer, and the
 * AI label are not stored inside links.
 */
export function buildIssueEmail(input: {
  issue: IssueEmailContent;
  language: EmailLanguage;
  senderName: string;
  links: IssueEmailLinks;
  russianFallback?: boolean;
}): IssueEmail {
  const copy = EMAIL_COPY[input.language];
  const lines: string[] = [input.senderName, input.issue.date, ''];
  for (const point of input.issue.summaryPoints) {
    lines.push(point, '');
  }
  for (const item of input.issue.items) {
    lines.push(...itemLines(item, copy.trial), '');
  }
  lines.push(copy.disclaimer, copy.aiLabel);
  if (input.russianFallback) {
    lines.push('', RUSSIAN_FALLBACK_NOTE);
  }
  lines.push(
    '',
    `${copy.unsubscribe}: ${input.links.unsubscribe}`,
    `${copy.privacy}: ${input.links.privacy}`,
    `${copy.issue}: ${input.links.issue}`,
  );

  const text = lines.join('\n');
  const htmlParts = [
    `<p>${escapeHtml(input.senderName)}</p>`,
    `<p>${escapeHtml(input.issue.date)}</p>`,
    ...input.issue.summaryPoints.map((point) => `<p>${escapeHtml(point)}</p>`),
    ...input.issue.items.map((item) => {
      const bits = itemLines(item, copy.trial).map((line) => `<p>${escapeHtml(line)}</p>`);
      return bits.join('');
    }),
    `<p>${escapeHtml(copy.disclaimer)}</p>`,
    `<p>${escapeHtml(copy.aiLabel)}</p>`,
  ];
  if (input.russianFallback) {
    htmlParts.push(`<p>${escapeHtml(RUSSIAN_FALLBACK_NOTE)}</p>`);
  }
  htmlParts.push(
    `<p><a href="${escapeHtml(input.links.unsubscribe)}">${escapeHtml(copy.unsubscribe)}</a></p>`,
    `<p><a href="${escapeHtml(input.links.privacy)}">${escapeHtml(copy.privacy)}</a></p>`,
    `<p><a href="${escapeHtml(input.links.issue)}">${escapeHtml(copy.issue)}</a></p>`,
  );

  return {
    subject: `${input.senderName} — ${input.issue.date}`,
    text,
    html: htmlParts.join('\n'),
  };
}
